# Generated by Django 4.2 on 2023-09-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_rename_title_contact_messege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time'], 'verbose_name_plural': 'News'},
        ),
    ]
